OUTPUT_DIR = "/home/dror/Projects/thesis/WRDS/output/%s"

HEADER = "PRIMEXCH,TRDSTAT,DCLRDT,DLAMT,DLPDT,DLSTCD,NEXTDT,PAYDT,RCRDDT,SHRFLG,DISTCD,DIVAMT,FACPR,FACSHR,ACPERM,ACCOMP,NWPERM,DLRETX,DLPRC,DLRET,TRTSCD,NMSIND,MMCNT,NSDINX,BIDLO,ASKHI,PRC,VOL,RET,BID,ASK,SHROUT,CFACPR,CFACSHR,OPENPRC,NUMTRD,RETX,vwretd,vwretx,ewretd,ewretx,sprtrn"

STOCK_RESULTS_FILE = "/home/dror/Projects/thesis/WRDS/scripts/stock_results.txt"
STOCK_NUMBERS = "/home/dror/Projects/thesis/WRDS/scripts/names_and_number.txt"
